services:
  mongo-container:
    image: 'mongo:6.0.7'
    restart: always
    environment:
      - 'MONGO_INITDB_DATABASE=quiz'
    logging:
      options:
        max-size: 1G
    ports:
      - '27017:27017'
